name:                haskell-notebook-language-server
version:             0.1.0.0

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- aeson
- attoparsec
- base >= 4.7 && < 5
- bytestring
- containers
- filepath
- ghc
- ghc-parser
- ghc-paths
- ihaskell
- lens
- lens-regex-pcre
- lsp-types
- monad-logger
- mtl
- myers-diff
- network-uri
- optparse-applicative
- pcre-light
- process
- regex-base
- regex-pcre-builtin
- retry
- safe
- string-interpolate
- text
- text-rope
- unix
- unliftio
- unliftio-core
- vector

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- ViewPatterns
- MultiWayIf
- TupleSections
- NumericUnderscores
- TypeApplications

library:
  source-dirs: src

executables:
  haskell-notebook-language-server:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -W
    dependencies:
    - haskell-notebook-language-server

tests:
  haskell-notebook-language-server-test:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -W
    dependencies:
    - haskell-notebook-language-server
    - QuickCheck
    - sandwich
    - sandwich-quickcheck
