name:                haskell-notebook-language-server
version:             0.1.0.0

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- containers
- ghc
- ghc-lib-parser
- ghc-parser
- ghc-paths
- ihaskell
- lsp-transformer
- lsp-types
- string-interpolate
- text

library:
  source-dirs: src

executables:
  haskell-notebook-language-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-notebook-language-server

  haskell-notebook-language-server-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-notebook-language-server
    - sandwich
