name:                haskell-notebook-language-server
version:             0.2.0.0

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- lsp-types >= 2.0.0.1
- monad-logger
- string-interpolate
- text
- unliftio

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- ViewPatterns
- MultiWayIf
- TupleSections
- NumericUnderscores
- TypeApplications

ghc-options:
- -Wunused-packages
- -Wall
- -fno-warn-name-shadowing

library:
  source-dirs: src
  dependencies:
  - aeson
  - containers
  - filepath
  - ghc
  - ghc-parser
  - ghc-paths
  - ihaskell
  - lens
  - lens-regex-pcre
  - pcre-light
  - mtl
  - myers-diff
  - network-uri
  - regex-base
  - regex-pcre-builtin
  - row-types
  - safe
  - text-rope
  - time
  - unliftio-core
  - vector

executables:
  haskell-notebook-language-server:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -W
    dependencies:
    - aeson
    - bytestring
    - ghc
    - ghc-paths
    - haskell-notebook-language-server
    - ihaskell
    - lens
    - mtl
    - optparse-applicative
    - process
    - retry
    - safe
    - unix
    - unliftio-core

tests:
  haskell-notebook-language-server-test:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -W
    dependencies:
    - containers
    - exceptions
    - haskell-notebook-language-server
    - QuickCheck
    - row-types
    - sandwich
    - sandwich-quickcheck
    - text-rope
