
resolver: lts-19.15

packages:
- .

extra-deps:
- git: https://github.com/codedownio/lsp-transformer.git
  # nix-sha256: 0tvwj79phsh99ca0cxa9a33vrc5a0wi8yp4cf469r0bamyjk54k6
  commit: 65b4e01bd931d080ad2fe592983d2f3c88f4f91e
