
resolver: lts-19.15

packages:
- .

extra-deps:
- git: https://github.com/codedownio/lsp-transformer.git
  # nix-sha256: sha256-t/SiboH6abwXKVhNwBwStKu5GeKHqOQ+NRHqKnvU/aU=
  commit: 65b4e01bd931d080ad2fe592983d2f3c88f4f91e
