
resolver: nightly-2022-02-01

packages:
- .

extra-deps:
- git: https://github.com/codedownio/lsp-transformer.git
  commit: 520bd819461f2b47d631e551badf1e05bdaa1cbf
  # nix-sha256: 1svwj79phsh99ca0cxa9a33vrc5a0wi8yp5cf469r0bamyjk54k6
